# This is a basic workflow to help you get started with Actions

name: Test Build

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    
defaults:
  run:
    shell: bash
    working-directory: .


jobs:
  build:
    name : Test APK
    runs-on: ubuntu-20.04
    
    steps:
      - name : Checkout
        uses: actions/checkout@v2
      
      - name : Gradle cache
        uses : actions/cache@v2
        with:
          path: |
            ~/.gradle/cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      
      - name: Change gradlew permissions
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Send Slack Bot
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEB_HOOK_URL }}
          SLACK_COLOR: '#FF5733'
          SLACK_TITLE: 'BUILD 성공했지만 실패했다고 테스트'
          MSG_MINIMAL: true
          SLACK_MESSAGE: '에러 확인 ㄱㄱㄱ'
